apiVersion: v1
kind: Pod
metadata:
  name: platform-lab-pod
  labels:
    app: platform-lab-solo
spec:
  containers:
    - name: app
      image: platform-lab:0.1.0
      ports:
        - containerPort: 8000
